### ISSUE TITLE
A tool to produce a CSV linking bundle members with file paths

### ISSUE THREAD

**Issue by esimpsons3ti** [SETI/pds-data-projects#20]
This module creates a .csv file listing the members of a bundle, their associated member status and reference types, and creates a list of paths to .xml and .lblx files associated with that collection term. 

The tool should be called `pds4_create_bundle_member_index.py`

The following specifications for this module:

1. Input argument should be described in comment (or docstring?) as the path containing the bundle.xml file.  Default should be the current directory.
2. Create `bundle_member_entries` (as done in `name_scraper_221209.py`), a list containing each instance of the Bundle_Member_Entry tag in bundle.xml
3. For each member of `bundle_member_entries`, find the LID (in `name_scraper_221209.py`, this was called `data_collection_term`, but I think `bundle_member_lid` would be a better name).  Create a dictionary `bundle_member_index` in which the key is the LID and the value is a list with three items, namely `member_status` and `reference_type` (both harvested from the lxml tree) and a blank string that you will later replace with the `path`. 
4. Use os.walk to look ONLY in the first level of subdirectories for files whose extension is `.lblx` or `.xml`
5. Using `lxml`, find the LID of each file found.  If it matches a key in the dictionary, then put its path into the corresponding place.  If it does not match any key in the dictionary, then create a line of output saying "PDS4 label found but not a member of this bundle: `<filepath>`, `<lid>`."
6. If there are any remaining entries in your dictionary whose paths have not been filled, throw an error.
7. Write the dictionary `bundle_member_index` into a file `bundle_member_index.csv`.

**Comment by matthewtiscareno** [comment]
I edited @esimpsons3ti's description above, in order to make items #2 and #3 more clear. 

The antecedent software `name_scraper_221209.py` is not on GitHub, but was posted by @esimpsons3ti to our Slack channel.

**Comment by matthewtiscareno** [comment]
To clarify: The tool that answers this issue should be given a single bundle.xml file and should create a CSV in the same directory with the characteristics described.  A different issue will cover the task of running this tool recursively.
