### ISSUE TITLE
A tool to produce a CSV linking collection members with file paths

### ISSUE THREAD

**Issue by esimpsons3ti** [SETI/pds-data-projects#21]
This tool creates a .csv file listing the members of a collection, their associated member status, LID, their associated VID, and the attributed path.

The tool should be called `pds4_create_collection_member_index.py`

The following specifications for this module:

1. Input argument should be described in comment (or docstring?) as the path containing the collection_*.xml file.  Default should be the current directory.

2. Using `lxml`, find the filename of the collection product (call it `collection_product_filename`) at `Product_Collection:File_Area_Inventory:File:file_name`

3. Open the file `collection_product_filename`, and read it.  Each line is comma-separated, with two elements (we should ask Mitch whether it’s okay to assume this in all cases).  The first is the `member_status` (either P for primary or S for secondary).  The second is the LIDVID, but parse this separately into the LID and the VID.  Create a dictionary `collection_member_index` in which the key is the LID and the value is a list with three items, namely the VID, the `member_status`, and a blank string that you will later replace with the path.

4. Use `os.walk` to look through all subdirectories for files whose extension is `.lblx` or `.xml`

5. Using `lxml`, find the LID of each file found.  If it matches a key in the dictionary, then put its path into the corresponding place.  If it does not match any key in the dictionary, then create a line of output saying "PDS4 label found but not a member of this bundle: `<filepath>`, `<lid>`." 

6. If there are any remaining entries in your dictionary whose paths have not been filled, throw an error.

7. Write the dictionary `collection_member_index` into a file `collection_member_index.csv`

**Comment by matthewtiscareno** [comment]
To clarify: The tool that answers this issue should be given a single collection_*.xml file and should create a CSV in the same directory with the characteristics described.  A different issue will cover the task of running this tool recursively.
